"""empty message

Revision ID: 08db61e018d5
Revises: f529e978815e
Create Date: 2023-06-18 00:38:02.155471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08db61e018d5'
down_revision = 'f529e978815e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'candidate', ['candidate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('candidate_id')

    # ### end Alembic commands ###
